" ~/.vimrc
"
" @author Augusto Pascutti

" Plugins {{{
" https://github.com/junegunn/vim-plug

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

let g:plug_url_format = 'git@github.com:%s.git'

call plug#begin('~/.vim/bundle')

" Essentials
Plug 'vim-syntastic/syntastic'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-sleuth'
Plug 'jistr/vim-nerdtree-tabs'
Plug 'editorconfig/editorconfig-vim'

" Fuzzy finder
Plug 'ctrlpvim/ctrlp.vim'
"let g:ctrlp_show_hidden=1
"let g:ctrlp_custom_ignore='\v[\/]\.(git|hg|svn)$'

" Project drawer (Fern)
Plug 'lambdalisue/fern.vim'
Plug 'lambdalisue/nerdfont.vim'
Plug 'lambdalisue/vim-fern-renderer-nerdfont'
Plug 'lambdalisue/vim-glyph-palette'
Plug 'lambdalisue/vim-fern-git-status'
let g:fern#renderer = "nerdfont"
map <C-n> :Fern . -reveal=% -drawer<CR>
function! s:init_fern() abort
  " Define NERDTree like mappings
  nmap <buffer> o <Plug>(fern-action-open:edit)
  nmap <buffer> t <Plug>(fern-action-open:tabedit)
  nmap <buffer> T <Plug>(fern-action-open:tabedit)gT
  nmap <buffer> i <Plug>(fern-action-open:split)
  nmap <buffer> gi <Plug>(fern-action-open:split)<C-w>p
  nmap <buffer> s <Plug>(fern-action-open:vsplit)
  nmap <buffer> gs <Plug>(fern-action-open:vsplit)<C-w>p
  nmap <buffer> ma <Plug>(fern-action-new-path)
  nmap <buffer> I <Plug>(fern-action-hidden-toggle)
  nmap <buffer> q :<C-u>quit<CR>
endfunction
augroup my-glyph-palette
  autocmd! *
  autocmd FileType fern call glyph_palette#apply()
  autocmd FileType fall-list call glyph_palette#apply()
  autocmd FileType nerdtree,startify call glyph_palette#apply()
augroup END

" Syntax or ecosystem plugins (loaded on demand)
Plug 'fatih/vim-go', { 'for': 'go', 'do': ':GoUpdateBinaries' }
Plug 'plasticboy/vim-markdown', { 'for': 'markdown' }
Plug 'pearofducks/ansible-vim', { 'for': 'yaml' }
Plug 'itspriddle/vim-shellcheck', { 'for': 'sh' }

" Vanity
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'catppuccin/vim', { 'as': 'catppuccin' }
let g:airline_theme="catppuccin_mocha"
Plug 'ryanoasis/vim-devicons'

" nvim plugins
if has("nvim")
    " Language Server Protocol
    Plug 'neovim/nvim-lspconfig'
    Plug 'hrsh7th/nvim-cmp'
    Plug 'hrsh7th/cmp-nvim-lsp'
    Plug 'hrsh7th/cmp-vsnip'
    Plug 'hrsh7th/vim-vsnip'
    Plug 'hrsh7th/cmp-nvim-lsp-signature-help'
    Plug 'folke/trouble.nvim'
    Plug 'onsails/lspkind.nvim'
    Plug 'williamboman/mason.nvim'
    Plug 'williamboman/mason-lspconfig.nvim'
    " Better syntax highlight
    Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
    " Colorscheme
    Plug 'catppuccin/nvim', { 'as': 'catppuccin' }
    " UX
    Plug 'nvim-lua/plenary.nvim'
    Plug 'nvim-telescope/telescope.nvim', { 'tag': '0.1.6' }
endif

call plug#end()
"}}}

" Visual Configuration {{{
set termguicolors
set background=dark
set t_Co=256
set encoding=UTF-8
colorscheme catppuccin_mocha
"}}}

" Global Maps {{{
nnoremap <leader>s :grep! "\b<C-R><C-W>\b"<CR>:copen<CR>
" }}}

" My Preferences {{{
set autoindent
set nowrap
set foldmethod=marker
set foldlevel=99    " fold level when opening a file
set incsearch
set hlsearch
set exrc
set sm              " show matching brackets
set ts=4            " tab stop
set et              " expand tabs
retab               " converts existing tabs
set ruler           " shows ruler
set laststatus=2   " lines of status
set nosmartindent   "
set novisualbell      " visual bell
set sw=4            " shift width (>)
set wildmode=longest,list:full
set guioptions=aAce
set cursorline      " highlugh current line
set number          " show line numbers (gutter-like)
set backspace=indent,eol,start
set tags=./.ctags,./tags,tags,~/.common_ctags
" }}}

" The silver searcher
if executable('ag')
    set grepprg=ag\ --nogroup\ --nocolor\ --column
    set grepformat=%f:%l:%c%m
    let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
    let g:ctrlp_use_caching = 0
endif
